function C = hempty(A)
    if A.blockType == 'L'
        UMat = zeros(A.height,0);
        VMat = zeros(A.width,0);
        C = struct('height',A.height,'width',A.width,...
                    'level',A.level,...
                    'trg',A.trg, 'src',A.src,...
                    'blockType',A.blockType,...
                    'UMat',UMat, 'VMat',VMat,...
                    'EPS',A.EPS, 'MAXRANK',A.MAXRANK, 'MINN',A.MINN);
    elseif A.blockType == 'D'
        DMat = zeros(A.height,A.width);
        C = struct('height',A.height,'width',A.width,...
                    'level',A.level,...
                    'trg',A.trg, 'src',A.src,...
                    'blockType',A.blockType,...
                    'DMat',DMat,...
                    'EPS',A.EPS, 'MAXRANK',A.MAXRANK, 'MINN',A.MINN);
    elseif A.blockType == 'H'
        childHMat = cell(4,4);
        for i = 1:4
            for j = 1:4
                childHMat{i,j} = hempty(A.childHMat{i,j});
            end
        end
        C = struct('height',A.height,'width',A.width,...
                    'level',A.level,...
                    'trg',A.trg, 'src',A.src,...
                    'blockType',A.blockType,...
                    'childHMat',{childHMat},...
                    'EPS',A.EPS, 'MAXRANK',A.MAXRANK, 'MINN',A.MINN);
    end
end